export const API_URL_GOC = 'https://5edc676811cb1d001665ce13.mockapi.io/dotq/'
export const API_CONGVIECS = API_URL_GOC + 'congviecs'
export const API_TOKENS = API_URL_GOC + 'tokens'
export const API_MEMBER_SIGNUP = API_URL_GOC + 'member_signup'
export const TASK_MANAGE = 'TASK_MANAGE'
export const LOGIN = 'LOGIN'
export const FORM_DANG_KI = 'FORM_DANG_KI'
